### PR TITLE
add support for custom tag names

### PR DESCRIPTION
**Pull request by ollevche**
Hey there! Thanks for your work on this wrapper, it helps a lot!

I've faced an issue with custom tag names set via `DecoderConfigOption`. Since `mapstructure` is hard coded here, we can't really override its value in `DecoderConfigOption`. Also, there is no way to get this value from viper so i added explicit setter to enviper

### CODE REVIEW

**Comment by iamolegga** [comment]
it looks like moved successfully, so please rebase on the latest master to trigger event for ci

**Comment by ollevche** [comment]
Hey, @iamolegga!

I have added a test but I have changed import paths locally to make it run successfully (since I forked your repo and it's a different module). I think it could lead to problems running it in your repo.

Please, start CI and check it out. Thanks!

**Comment by iamolegga** [comment]
@ollevche thanks, but tests failed, please run `go mod tidy` to add deps and commit.

Also I'm wondering if it's possible to keep API same as `viper` without adding extra methods but getting tagname somehow from viper opts?

**Comment by iamolegga** [comment]
I think we can drop failed test `func TestNew`, it's not required anymore if we are changing config

**Comment by ollevche** [comment]
@iamolegga I think better to fix tests and provide a public getter (it could be helpful for someone)

**Comment by ollevche** [comment]
@iamolegga

> Also I'm wondering if it's possible to keep API same as viper without adding extra methods but getting tagname somehow from viper opts?

Unfortunately, no. It's set in `DecoderConfigOption` that is passed directly to `mapstruture` and we can't get tag name value before processing

**Comment by iamolegga** [comment]
OK then. Let's just add some docs on this feature and I'll merge and release it 👍

**Comment by iamolegga** [comment]
Comments for godoc and a couple of words in a readme

**Comment by ollevche** [comment]
@iamolegga done!

**Comment by iamolegga** [comment]
released in `v1.4.0` 🙌

**Pull request merged**
